### ISSUE TITLE
Usage of scikit-learn ``QuantileRegressor`` for ``scipy-linprog`` solver

### ISSUE THREAD

**Issue by Badr-MOUFAD** [benchopt/benchmark_quantile_regression#11]
While browsing the source code of scikit-learn's [``QuantileRegressor``](https://github.com/scikit-learn/scikit-learn/blob/dc580a8ef/sklearn/linear_model/_quantile.py#L20),
I found that the implementation we use in ``scipy-linprog`` solver is quite the same.

Is there a reason for not using ``scikit-learn`` ``QuantileRegressor`` and passing in ``solver_options`` to the estimator to customize ``scipy`` solver?

**Comment by mathurinm** [comment]
I guess it makes sense to access directly the solver and not its sklearn wrapper ? Eg sklearn can decide to change its implementation any day and then the benchmark changes unknowingly

**Comment by Badr-MOUFAD** [comment]
Got it thanks!
